version: '3.4'
name: 'quokkadevtemplates_dev_environment'

networks:
  proxynet:
    driver: bridge
  
# Change volumes names
volumes:   
  quokkadevtemplates_sql_volume:
    external: true
  quokkadevtemplates_seq_volume:
    external: true
  quokkadevtemplates_key_volume:
    external: true
  # quokkadevtemplates_blob_volume:
  #   external: true
  # quokkadevtemplates_smtp_volume:
  #   external: true

services:
  QuokkaDev.Templates.Api:
    image: ${DOCKER_REGISTRY-}quokkadevtemplatesapi
    container_name: quokkadevtemplates_api_dev_instance
    build:
      context: .
      dockerfile: src/QuokkaDev.Templates.Api/Dockerfile
    environment:
      - ConnectionStrings__Default=${ConnectionStrings__Default}
      - Serilog__WriteTo__0__Args__serverUrl=${Serilog__WriteTo__0__Args__serverUrl}
    volumes:
      - quokkadevtemplates_key_volume:/root/.aspnet/DataProtection-Keys     
    depends_on:
      - sql
      - seq
      # - smtp
      
  sql:
    image: ${DOCKER_REGISTRY-}mcr.microsoft.com/mssql/server:2022-latest
    container_name: quokkadevtemplates_sql_dev_instance
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyS@P@55w0rd!
    volumes:
      - quokkadevtemplates_sql_volume:/var/opt/mssql
    ports:
      - "1433:1433"

  seq:
    image: datalust/seq:latest
    container_name: seq_dev_instance
    hostname: seq
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - quokkadevtemplates_seq_volume:/data
    ports:
      - "5001:80"
      - "5341:5341"

  # azurite:
  #   image: mcr.microsoft.com/azure-storage/azurite
  #   container_name: quokkadevtemplates_blob_dev_instance
  #   hostname: azurite
  #   volumes:
  #     - quokkadevtemplates_blob_volume:/data
  #   ports:
  #     - "10000:10000"
  #     - "10001:10001"
  #     - "10002:10002"
  
  # smtp:
  #   image: ${DOCKER_REGISTRY-}rnwood/smtp4dev:latest
  #   container_name: quokkadevtemplates_smtp_dev_instance
  #   volumes:
  #     - quokkadevtemplates_smtp_volume:/smtp4dev
  #   ports:
  #     - "5000:80"
  #     - "25:25"
  #     - "143:143" 