name: Build NuGet package and VSIX

on:
  push:
    branches: main

jobs:
  build-vsix:    
    runs-on: windows-latest

    outputs:
      version: ${{ steps.calculate_version.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3      
        with:
          fetch-depth: 0

      - name: Calculate version
        uses: paulhatch/semantic-version@v4.0.2
        id: calculate_version        
        with: 
          tag_prefix: "v"        
          major_pattern: "(MAJOR)"        
          minor_pattern: "(MINOR)"        
          format: "${major}.${minor}.${patch}" 
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.6
        
      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE    
        
      - name: Restore Packages
        run: nuget restore ./src/QuokkaDevVSIXTemplates/QuokkaDevVSIXTemplates.sln
 
      - name: Update VSIX version
        run: |
          .\Update-Version.ps1 ${{ steps.calculate_version.outputs.version }}

      - name: Build Solution
        run: |
          msbuild.exe ./src/QuokkaDevVSIXTemplates/QuokkaDevVSIXTemplates.sln /nologo /nr:false /p:platform="Any CPU" /p:configuration="Release"
          
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:  
          name: QuokkaDevVSIXTemplates.${{ steps.calculate_version.outputs.version }}.vsix
          path: "./src/QuokkaDevVSIXTemplates/QuokkaDevVSIXTemplates/bin/Release/QuokkaDevVSIXTemplates.vsix"      

  build-nuget-package:
    needs: build-vsix
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ['6.0.x' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3      
        with:
          fetch-depth: 0
      
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      
      - name: Prepare nuget source
        run: dotnet nuget add source --username demonpie --password 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 --store-password-in-clear-text --name github "https://nuget.pkg.github.com/QuokkaDevit/index.json"
      
      # Build templates

      - name: Build QuokkaDevCleanArchitectureSolution
        run: dotnet build --configuration Release src/templates/QuokkaDevCleanArchitectureSolution/QuokkaDev.Templates.sln

      - name: Build QuokkaDevPackage
        run: dotnet build --configuration Release src/templates/QuokkaDevPackage/QuokkaDev.Package.sln
      
      - name: Install dependencies
        run: dotnet restore src/QuokkaDev.Templates.Collection.csproj   

      # End Build templates
      
      - name: Pack QuokkaDev.Templates.Collection
        run: dotnet pack src/QuokkaDev.Templates.Collection.csproj -c Release /p:NoDefaultExcludes=true /p:Version=${{ needs.build-vsix.outputs.version }}
      
      - name: Publish to GitHub package QuokkaDev.Templates.Collection 
        run: dotnet nuget push src/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:  
          name: QuokkaDev.Templates.Collection.${{ needs.build-vsix.outputs.version }}.nupkg
          path: src/bin/Release/*.nupkg

      # Tag version and create release

      - name: Tag version v${{ needs.build-vsix.outputs.version }}
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "v${{ needs.build-vsix.outputs.version }}"
          message: "v${{ needs.build-vsix.outputs.version }}"

      - name: Download VSIX
        uses: actions/download-artifact@v3
        with:
          name: QuokkaDevVSIXTemplates.${{ needs.build-vsix.outputs.version }}.vsix

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          configuration: "configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.build-vsix.outputs.version }}
          release_name: Release v${{ needs.build-vsix.outputs.version }}
          draft: false
          prerelease: false
          body: ${{steps.github_release.outputs.changelog}}

      - name: Upload NuGet Package to Release
        id: upload-release-asset-1 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: src/bin/Release/QuokkaDev.Templates.Collection.${{ needs.build-vsix.outputs.version }}.nupkg
          asset_name: QuokkaDev.Templates.Collection.${{ needs.build-vsix.outputs.version }}.nupkg
          asset_content_type: application/x-msdownload

      - name: Upload VSIX to Release
        id: upload-release-asset-2
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: QuokkaDevVSIXTemplates.vsix
          asset_name: QuokkaDevVSIXTemplates.${{ needs.build-vsix.outputs.version }}.vsix
          asset_content_type: application/vsix